### ISSUE TITLE
Not surprised 

### ISSUE THREAD

**Issue by skylarr1227** [thecrimsonsword/mewbot-images#1]
We're talking about a literal crook from Nigeria who was caught scamming and stealing along with using the dark web to obtain stolen identity documents and more....

However good to have confirmation of what was already known to be true 😂

**Comment by PayYourTaxes** [comment]
Not surprised the hypocrisy continues. Shouldn’t you get a job and pay the IRS back?

https://user-images.githubusercontent.com/117413190/199855000-6ce44131-ae4f-4a84-97a1-718ba9cf48d2.MOV

**Comment by skylarr1227** [comment]
nice try idiot, but that simply doesnt exist in our bot <3

**Comment by PayYourTaxes** [comment]
It was probably just removed but the proof is still there. Get ready cause we aren’t done. 

I do one thing that isn’t removed. Your debt to the IRS LOL

**Comment by skylarr1227** [comment]
Not scared of a bunch of thieves. Not at all. Idiots.

**Comment by PayYourTaxes** [comment]
Should be scared of the government.

**Comment by skylarr1227** [comment]
Im not, its already been paid. Thanks for the concern though. And clearly accepting that it was infact true.

**Comment by PayYourTaxes** [comment]
You’d know it was true because it was uploaded when you ran the bot. Your $2,000 donated requirement for custom Pokémon that your team uploaded. It screams clown energy. 

Doesn’t look paid per the announcement in your discord. “Hopefully the IRS allows a payment plan” on top of the 17k balance but you don’t have a job. Lies and more lies.

**Comment by skylarr1227** [comment]
![image](https://user-images.githubusercontent.com/44381751/199858069-b6ac8adf-6a4c-449a-be4a-4b448fe8de3f.png)
any images we use, we have the artist credited, because we ask them.

**Comment by PayYourTaxes** [comment]
Then why was it removed from your bot Lmaoo. Lies don’t fool anyone.

**Comment by skylarr1227** [comment]
Also, funny-your entire bot is literally a copy of ours. And its admitted in the open.

**Comment by skylarr1227** [comment]
![image](https://user-images.githubusercontent.com/44381751/199858256-35c88fc6-b561-44cf-9e16-235744abcc39.png)
weird

**Comment by PayYourTaxes** [comment]
Bot is a copy of people’s work that you just took. Cause you wouldn’t know the first thing about coding apparently lol

**Comment by skylarr1227** [comment]
Weird. Its like you arent worth my time, because you will argue with anything, have a good night idiot.

**Comment by skylarr1227** [comment]
done

**Comment by PayYourTaxes** [comment]
Bet anyone that doesn’t automatically think your right isn’t worth your time. Go get your payment plan in place. Ill go enjoy my paycheck from my employer LOL

**Comment by PayYourTaxes** [comment]
![C768865E-24DB-48E4-B72E-01287CFE73B0](https://user-images.githubusercontent.com/117413190/199858649-203d2c3d-e6f9-4e93-94df-d87cbbf32167.png)

**Comment by PayYourTaxes** [comment]
![79593D69-CBA1-44B4-BFB9-4AE0E996E120](https://user-images.githubusercontent.com/117413190/199858985-782c5060-fd23-4020-a1d3-1c5035b4a10f.png)
